# 大模型配置
baseurl: https://api.example.com/v1  # API基础URL
key: your-api-key-here  # API密钥
model: gpt-4  # 模型名称
temperature: 0.7  # 生成温度
max_tokens: 2048  # 最大token数
timeout: 30  # 请求超时时间(秒)
stream: false  # 是否流式输出
